---
output:
  pdf_document: default
  html_document: default
---

#Definir JSONS
```{r}
library(ggplot2)
library(magrittr)
library(dplyr)

readCsv <- function(x) {
    result <- read.csv(file = paste('./cc/', x, sep = ''))
}

toFrame <- function(cc, q_name, mode = "cc", v = data.frame()) {
  tmp <- 1:nrow(v)
  for (i in 1:nrow(v)) tmp = q_name
  
  v = data.frame(cc)[1]
  v = data.frame(v[order(v),])
  
  tmp_mode <- 1:nrow(v)
  for (i in 1:nrow(v)) tmp_mode[i] = mode
  
  v = data.frame(1:nrow(v), v, tmp, tmp_mode)
  colnames(v) <- c('x', 'y', 'queue', 'mode')
  result <- v
}

cc_file_names = list.files(path="./cc", pattern="*.csv")
cc <- lapply(cc_file_names, readCsv)
cc_tmp <- read.csv(text="x, y, queue")


for (i in 1:length(cc)) {
  cc_tmp <- rbind(cc_tmp, toFrame(cc[i], cc_file_names[i], "cc"))
}

cc_tmp$y <- cc_tmp$y / 1000000 

#scale_x_discrete(labels= c('iteration', 'ops/sec', 'queue'))
ggplot(data.frame(cc_tmp), aes(x = x, y = y)) + geom_line(aes(colour = queue)) + xlab('iteration') + ylab('million ops/sec') + scale_x_continuous(breaks = round(seq(min(cc_tmp$x), max(cc_tmp$x), by = 1),1)) + scale_y_continuous(breaks = round(seq(0, max(cc_tmp$y) + 20, by = 20),0)) + ggtitle('Cross Core')

```

```{r}
readCsv <- function(x) {
    result <- read.csv(file = paste('./sc/', x, sep = ''))
}

sc_file_names = list.files(path="./sc", pattern="*.csv")
sc <- lapply(sc_file_names, readCsv)
sc_tmp <- read.csv(text="x, y, queue")


for (i in 1:length(sc)) {
  sc_tmp <- rbind(sc_tmp, toFrame(sc[i], sc_file_names[i], "sc"))
}

sc_tmp$y <- sc_tmp$y / 1000000 

#scale_x_discrete(labels= c('iteration', 'ops/sec', 'queue'))
ggplot(data.frame(sc_tmp), aes(x = x, y = y)) + geom_line(aes(colour = queue)) + xlab('iteration') + ylab('million ops/sec') + scale_x_continuous(breaks = round(seq(min(sc_tmp$x), max(sc_tmp$x), by = 1),1)) + scale_y_continuous(breaks = round(seq(0, max(sc_tmp$y) + 20, by = 20),0)) + ggtitle('Single Core')

```

```{r}
readCsv <- function(x) {
    result <- read.csv(file = paste('./cs/', x, sep = ''))
}

cs_file_names = list.files(path="./cs", pattern="*.csv")
cs <- lapply(cs_file_names, readCsv)
cs_tmp <- read.csv(text="x, y, queue")


for (i in 1:length(cs)) {
  cs_tmp <- rbind(cs_tmp, toFrame(cs[i], cs_file_names[i], "cs"))
}

cs_tmp$y <- cs_tmp$y / 1000000 

#scale_x_discrete(labels= c('iteration', 'ops/sec', 'queue'))
ggplot(data.frame(cs_tmp), aes(x = x, y = y)) + geom_line(aes(colour = queue)) + xlab('iteration') + ylab('million ops/sec') + scale_x_continuous(breaks = round(seq(min(cs_tmp$x), max(cs_tmp$x), by = 1),1)) + scale_y_continuous(breaks = round(seq(0, max(cs_tmp$y) + 20, by = 20),0)) + ggtitle('Cross Socket')

```
```{r}

all <- rbind(cc_tmp, cs_tmp, sc_tmp)

for (name in cc_file_names) {
  all_by_queue = all[all$queue == name, ]
  p <- ggplot(data.frame(all_by_queue), aes(x = x, y = y)) + geom_line(aes(colour = mode)) + xlab('iteration') + ylab('million ops/sec') + scale_x_continuous(breaks = round(seq(min(all_by_queue$x), max(all_by_queue$x), by = 1),1)) + scale_y_continuous(breaks = round(seq(0, max(all_by_queue$y) + 10, by = max(all_by_queue$y)/10),0)) + ggtitle(name)
  print(p)
}

```

